# Generated by Django 2.1.7 on 2019-02-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_address', '0002_auto_20160213_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('locality', 'route', 'street_number', 'subpremise'), 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddField(
            model_name='address',
            name='subpremise',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
